export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT'


export const ACTION_SELECT_ORDER = 'ACTION_SELECT_ORDER';
export const ACTION_GET_ORDERS = 'ACTION_GET_ORDERS';
