export const AUTHORISATION_REQUEST = 'AUTHORISATION_REQUEST';
export const AUTHORISATION_SUCCESS = 'AUTHORISATION_SUCCESS';
export const AUTHORISATION_ERROR = 'AUTHORISATION_ERROR';

export const INITIAL_PROFILE_REQUEST = 'INITIAL_PROFILE_REQUEST';
export const INITIAL_PROFILE_SUCCESS = 'INITIAL_PROFILE_SUCCESS';
export const INITIAL_PROFILE_ERROR = 'INITIAL_PROFILE_ERROR';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';

export const SEND_ORDERS_REQUEST = 'SEND_ORDERS_REQUEST';
export const SEND_ORDERS_SUCCESS = 'SEND_ORDERS_SUCCESS';
export const SEND_ORDERS_ERROR = 'SEND_ORDERS_ERROR';

export const ACTION_SELECT_ORDER = 'ACTION_SELECT_ORDER';